### ISSUE TITLE
Lightning Specification Meeting 2022/06/20

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1002]
The meeting will take place on Monday 2022/06/20 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Pull Request Review

- [x] Zero conf nits #998
- [x] Channel update flags #996 or #999
- [x] Grace period for older channel updates #1001
- [ ] ~Clarify coop close requirements #970~
- [ ] ~Route blinding #765~
- [x] Hold htlcs before forwarding #989
- [ ] ~Onion messages #759~
- [ ] ~Offers #798~
- [x] Add dust exposure threshold #919
- [ ] ~Taproot #995~

## Waiting for interop

- [ ] ~Handle `update_fee` during `shutdown` #972~
- [ ] ~Graph dump on `gossip_timestamp_filter` #980~
- [ ] ~Dual funding #851~
- [ ] ~Websocket transport #891~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~
- [ ] ~Dynamic DNS support in gossip messages #911~

## Long Term Updates

- [ ] ~Liquidity ads #878~
- [ ] ~Splicing #863~
- [ ] ~Simplified commitment #867~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Peer storage backup #881~
- [ ] ~Anonymous gossip~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~
