### ISSUE TITLE
Lightning Specification Meeting 2022/08/01

### ISSUE THREAD

**Issue by Roasbeef** [lightning/bolts#1015]
The meeting will take place on Monday 2022/07/04 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Pull Request Review
- [x] channel update pruning clarification: https://github.com/lightning/bolts/pull/1014
- [x] Channel update flags #996 or #999
- [x] Grace period for channel closes #1004
- [x] fee range clarification: https://github.com/lightning/bolts/issues/1013
- [x] Route blinding #765
- [x] Onion messages #759
- [x] Offers #798
- [x] Add dust exposure threshold #919
- [x] Taproot #995
- [x] Dynamic DNS support in gossip messages #911

## Waiting for interop

- [ ] Handle `update_fee` during `shutdown` #972
- [x] Graph dump on `gossip_timestamp_filter` #980
- [ ] Dual funding #851
- [x] Websocket transport #891
- [x] Don't force close until error is received after `channel_reestablish` #934

## Long Term Updates

- [ ] Pinning attacks as related to: splicing, dual funding, dynamic commitments: https://github.com/lightning/bolts/pull/863#issuecomment-1177778091
- [ ] Liquidity ads #878
- [ ] Splicing #863
- [ ] Simplified commitment #867
- [ ] Hold htlcs before forwarding #989
- [ ] Trampoline routing #829 and #836
- [ ] Upfront payments / DoS protection #843
- [ ] Peer storage backup #881
- [ ] Anonymous gossip

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] lnprototest (https://github.com/rustyrussell/lnprototest)

**Comment by Roasbeef** [comment]
Legacy onion format update:
  * latest lnd release switches the "send to route" call to use the modern payload
  * t-bast still seeing some legacy onion payloads, around 5%
 
HTLC max stuff:
  * Trivial number not setting, it should be g2g

Actions:
  * #1014:
     * matches 
  * #999:
      * needs interop 
  * #1004:
      * potential interactions w/ splicing and pinning, but seem somewhat unrelated
      * no major contests
  * #1013:
       * related to some idea re a turn based protocol for the simple taproot channels 
       * agreement that a new warning message (w/ an error code) would make things less ambiguous 
       * lnd working on fully implementing it
  * #765 
       * routing blinding! lnd has a PR now for the crypto bits
       * new ideas re error messages:
            * if you get an unexpected error, then you need to reject it w/ "bad onion" (invoice expires, already paid, etc)
                 * the node that straddles the path (part blinded, part plaintext) will always send the bad onion
            * alternative: all failures look the same 
            * if you get mpp timeout, then can use that to re-split the payment?
       * implementations now moving on to implementing the sending+receiving side of things 
       * t-bast wanting to regenerate the test vectors, waiting for a real concept ACK on the TLVs (last commit of the PR)
   * #759 
       * rusty might be rolling it back to 33 byte pubkeys, easy to make backwards compatible 
       * nothing much has changed
       * fork of lnd exists that has it working (?)
       * should it be 100% route blinded?
   * #919
       * new version seems to be cleaned up, ready for another round for review? 
       * fwiw, most implementations have already implemented some form of this, but now we want to codify it in the spec 
   * #955
       * laolu shooting to get end demo out as a PR this week, few other things to respond to 
       * possile thread to spin out here re turn based protoocl for co-op close
       * in gossip 1.5 should we go for just block based timestamps instead?
   * #980
       * trinary mode: send all, send none, send 2 weeks 
     
Interop updates:
  * DNS and webscoetks extensisons looking g2g, clear to merge
      * lnd 0.15 will now properly allow them to propgate (ingoring unkonwn node addr types)

**Comment by t-bast** [comment]
Thanks for the summary laolu! Here are more details on the route blinding discussion about error messages.

The current state of the PR says that whenever an error occurs inside the blinded path, nodes must return a malformed onion (with `update_fail_malformed_htlc`) to ensure no data from within the blinded path can leak and reveal private information (probing protection). Nodes inside the blinded path should also transform normal errors into malformed errors: this way even if one node is misbehaving and sending a normal error, this can be corrected by other nodes inside the blinded path.

This strategy is quite extreme. We may want to allow some information to be propagated back to the sender for some failure cases. The proposal from @rustyrussell is that the final node can be allowed to send normal errors (`update_fail_htlc`) for a few cases, such as MPP timeout. Intermediate nodes should still only use `update_fail_malformed_htlc` for their own errors, but shouldn't transform normal errors into malformed errors anymore.

The risk with that proposal is that a misbehaving node who is next-to-last can now send a normal error (instead of a malformed one) and other nodes in the blinded will not correct it by transforming it into a malformed error, potentially giving the sender private information that would let them probe the identity of the recipient. However, if such a next-to-last node was malicious, they probably have other ways of exposing the recipient, and can simply deny them the payment, so maybe we shouldn't care about such scenario?

I don't have a definite answer yet, @thomash-acinq and I will spend more time on the implementation and will report back.
