### ISSUE TITLE
 Lightning Specification Meeting 2022/08/15

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1017]
The meeting will take place on Monday 2022/08/15 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Pull Request Review

- [x] Clarify bolt 4 blinding #1012
- [x] Channel update pruning clarification: #1014
- [x] Channel update flags #996 or #999
- [x] Grace period for channel closes #1004
- [x] Closing fee range turn-based protocol #1016
- [x] Route blinding #765
- [x] Onion messages #759
- [x] Offers #798
- [x] Add dust exposure threshold #919
- [x] Taproot #995

## Waiting for interop

- [x] Dual funding #851
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~
- [ ] ~Graph dump on `gossip_timestamp_filter` #980~
- [ ] ~Handle `update_fee` during `shutdown` #972~
- [x] Websocket transport #891

## Long Term Updates

- [x] Pinning attacks as related to splicing / dynamic commitments: https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-August/003665.html
- [ ] ~Liquidity ads #878~
- [x] Splicing #863
- [ ] ~Simplified commitment #867~
- [ ] ~Hold htlcs before forwarding #989~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Peer storage backup #881~
- [ ] ~Anonymous gossip~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by Roasbeef** [comment]
Co-op close commentary: https://github.com/lightning/bolts/pull/1016#issuecomment-1215752091

**Comment by Roasbeef** [comment]
Route blinding commentary:
  * Originally: mug all errors, turn it into a different error (very opaque)
  * More recent ideas: ideally we can propagate well formed errors that are useful (mpp timeout, etc). Important that the error needs to be wrapped in the _blinded_ key rather than your actual key
  * Now wrangling the wording in the spec, with the test vectors updated as well. 
  * CL has updated code, works w/ the test vectors. Now working on doing an e2e test w/ blinded paths for _payments_ 
  * Future requests: want a persistent fake identity for the final hop as well? Something to be done in the future potentially. 
  * Blinded payments now also compulsory for BOLT 12, you want to also supply one even if you don't need it. Gives you sort of mandatory payment secrets

**Comment by Roasbeef** [comment]
Offers commentary:
  * Right now you ignore certain numbered fields that store signatures, or are included in signatures 
  * Some want to have _two_ distinct streams: one stream for the things hashed, and another stream for the sigs
  * Might want to add some more distinct layers, some feel like it can be inefficient

**Comment by Roasbeef** [comment]
web sockets commentary (#891):
  * Host name merged in now. Turns out web sockets must always be HTTPs for browsers, so you need a cert, which means you need a host name. 
  * Now seems we want a _new_ explicit type, to indicate it's web sockets only, with maybe also a bit to set if TLS is required or not.

**Comment by Roasbeef** [comment]
dual funding (#851):
  * CL uses anchor outputs always, eclair starting to implement but doesn't always have anchors 
  * related threads re splicing and pinning stuff above

**Comment by niftynei** [comment]
> CL uses anchor outputs always, eclair starting to implement but doesn't always have anchors

eclair has implemented fwiw! "Dual funding PRs are being merged to master (#2247, #2273, #2274, #2275)"

**Comment by t-bast** [comment]
Thanks for the summary @Roasbeef, much appreciated!
