### ISSUE TITLE
Lightning Specification Meeting 2022/10/24

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1033]
The meeting will take place on Monday 2022/10/24 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Relax forwarding amount instructions #1025, #1031 and #1032
- [x] Dual funding #851
- [x] Anchor outputs zero fee htlc txs test vectors #1018
- [x] Tlv stream in onion failures #1021
- [x] Add dust exposure threshold #919

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Route blinding #765~
- [ ] ~Onion messages #759~
- [ ] ~Offers #798~
- [ ] ~Taproot #995~
- [ ] ~Closing fee range turn-based protocol #1016~
- [ ] ~Update static channel parameters #1026~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Fix channel pruning behavior~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~
- [ ] ~Graph dump on `gossip_timestamp_filter` #980~
- [ ] ~Websocket transport #891~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Pinning attacks as related to splicing / dynamic commitments: https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-August/003665.html~
- [ ] ~Liquidity ads #878~
- [ ] ~Quiescence #869~
- [ ] ~Splicing #863~
- [ ] ~Simplified commitment #867~
- [ ] ~Hold htlcs before forwarding #989~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Upfront payments / DoS protection #843 and https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-August/003673.html~
- [ ] ~Peer storage backup #881~
- [ ] ~Anonymous gossip~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by t-bast** [comment]
We're entering DST mess, not 100% sure I got the meeting time right, I may update it at the last minute if it's wrong, watch closely.

**Comment by joostjager** [comment]
Fat errors: https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-October/003723.html

**Comment by ariard** [comment]
Updated #919 with the edit suggested.

**Comment by Roasbeef** [comment]
relaxing recipient requirements:
  * equality vs inequality 
  *  to keep intermediate nodes as they are (you get more fees), but last node being more lax 
     * would then mean that responders would accept more 
     * otherwise potentially a probing vector 
  * main PRs #1032 which builds on #1031
      * receivers can just update at all, resolves the last mile probing from the PoV of the value 
      * two layers: mpp level relaxing, and also onion level relaxing -- both in the PRs above 
   * discussion w.r.t if we need to add a feature bit or not: when can the sender start to send _more_ than the amount
       * can cause failures otherwise trigger failures if one tries to use this feature w/o the sender having being upgraded
       * may be able to get by or not....
       * question of if we should get rid of `min_hltc`, but then people would still enforce the value 

dual funding + interactive tx:
  * interop between eclair and CLN now finished 
  * few open questions:
       * rn input ordering: provide input for each input, then order the input ordering according to that
       * question that we use that instead of BIP 69, since we're not using that, then LN txns will differ 
       * not using BIP 69 gives ppl more flexibility, to do fancier sighash stuff in the future 
   * who sends signature first? 
       * if one sends the sigs first, then one party can broadcast but the other party doesn't 
       * if opener always sends the signatures, then you can't batch two funding transactions 
       * proposal:
            * allows initiator to defer sending the signature w/ a TLV to allow tx batching 
       * current: the side w/ the most sats inputs signs first 
       * or: the person w/ the most inputs, since they need to spend the most to double spend
    * restrictions on inputs:
       * can specify to reject inputs that aren't confirmed 
       * related to splicing, then makes a lot of unconfirmed generations of transactions as well

anchor output tx test vectors:
  * on the TOOD list for CLN+lnd, LDK has it merged, PR up to eclair 

tlv streams in failures:
   * last question: wanting to add a feature bit to signal things 
   * implications for feature bits and forwarding:
      * implications for path finding and also intermediate nodes? 
      * seems lnd will forward it, but the sender errors out
      * if you're the sender then: 
           * the intermediate node erroring, doesn't know if the sender supports it or not 
           * so you want a feature bit _in_ the onion as well 
       * potentially privacy leak:
          * sender (of the payments) identifies themselves in the onion (they know this new feature)
          * only exists until others don't do it, arguably a similar leak exists w/ feature bits as is, onion space hasn't been modified in a while 
              * other stuff like forwarding passes or other stuff would also start to use this intermediate onion space
   * related to revamped fat errors (lets the sender pinpoint who sent the error) wants larger errors as well

dust level spec advice:
  * new version, t-bast has ack'd, ready for other review
