### ISSUE TITLE
Lightning Specification Meeting 2022/12/05

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1046]
The meeting will take place on Monday 2022/12/05 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Tlv stream in onion failures #1021
- [x] Add dust exposure threshold #919
- [x] Route blinding #765
- [x] Fat errors #1044
- [x] Anchor outputs zero fee htlc txs test vectors #1018
- [x] Dual funding #851
- [x] Issue with the `cltv_expiry_delta` section? #1045

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [x] Onion messages #759
- [x] Offers #798
- [x] Taproot #995
- [x] Closing fee range turn-based protocol #1016
- [x] Update static channel parameters #1026
- [ ] ~Sign commitments at various feerates #1036~
- [x] Liquidity ads #878

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Fix channel pruning behavior -> fixed in eclair, lnd was already fixed, what about ldk and cln?~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~
- [ ] ~Graph dump on `gossip_timestamp_filter` #980~
- [ ] ~Websocket transport #891~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Channel jamming #1043~
- [ ] ~Pinning attacks as related to splicing / dynamic commitments: https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-August/003665.html~
- [ ] ~Quiescence #869~
- [ ] ~Splicing #863~
- [ ] ~Simplified commitment #867~
- [ ] ~Hold htlcs before forwarding #989~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Peer storage backup #881~
- [ ] ~Anonymous gossip~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by t-bast** [comment]
I won't be able to attend this spec meeting, I'll let you guys get all of those PRs merged :wink: 
Can someone record the meeting so that we try using a tool to generate the transcript?

**Comment by Roasbeef** [comment]
@t-bast I have a recording of the transcript, I'm gonna try this new fancy AI transcription software to see how it does (will post results here): https://github.com/openai/whisper

**Comment by t-bast** [comment]
Nice, thanks @Roasbeef !

**Comment by Roasbeef** [comment]
Here's the transcript: https://gist.github.com/Roasbeef/24533cd0cfc5310e530af96afd1e2b2b

I used the "medium" model on my laptop, and it's pretty good though there're some weird words in there. 

This is the command I used to generate the transcript: 
```
whisper Lightning-Spec-Meeting_2022-12-05T20_00_19.967Z.webm --model medium
``` 

The default download from the jitsi was `webm`.

**Comment by t-bast** [comment]
There are some parts that lost me ("I mean, so Vinyl Flask 2023 is what it sounds like.") but it's really nice to have a transcript, I was able to go through everything that was discussed, so that looks like a good option, thanks @Roasbeef !

**Comment by Roasbeef** [comment]
Heh I think, that was "blinded paths 2023"

**Comment by ariard** [comment]
Thanks for the transcripts! Really valuable to have them.
