### ISSUE TITLE
Lightning Specification Meeting 2022/12/19

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1047]
The meeting will take place on Monday 2022/12/19 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Dual funding #851
- [x] Route blinding #765
- [ ] ~Add dust exposure threshold #919~
- [ ] ~Fat errors #1044~
- [ ] ~Anchor outputs zero fee htlc txs test vectors #1018~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Onion messages #759~
- [ ] ~Offers #798~
- [ ] ~Taproot #995~
- [ ] ~Closing fee range turn-based protocol #1016~
- [ ] ~Update static channel parameters #1026~
- [ ] ~Sign commitments at various feerates #1036~
- [ ] ~Liquidity ads #878~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Tlv stream in onion failures #1021 -> implemented in lnd and eclair, needs interop test~
- [ ] ~Fix channel pruning behavior -> fixed in eclair, lnd was already fixed, what about ldk and cln?~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~
- [ ] ~Graph dump on `gossip_timestamp_filter` #980~
- [ ] ~Websocket transport #891~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Channel jamming #1043~
- [ ] ~Pinning attacks as related to splicing / dynamic commitments: https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-August/003665.html~
- [ ] ~Quiescence #869~
- [ ] ~Splicing #863~
- [ ] ~Simplified commitment #867~
- [ ] ~Hold htlcs before forwarding #989~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Peer storage backup #881~
- [ ] ~Anonymous gossip~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by t-bast** [comment]
Right, if most people are on holidays let's push this one to January. I'll be around just in case @niftynei or @rustyrussell are around because there's a couple things I'd like to discuss with them, but no pressure, if not let's just skip this.

**Comment by rustyrussell** [comment]
@niftynei and I are actually on the call RN, @t-bast

**Comment by t-bast** [comment]
Meeting nodes regarding the dual funding PR:

- feature dependency on `option_static_remotekey` will be removed
- we will remove the recently introduced `est_witness_weight`
- the `second_per_commitment_point` was added to `open_channel2`, needs to be added to `accept_channel2`
- we simply ignore its duplicated value in `channel_ready` for simplicity (may reuse that field for something else in the long term future)

Meeting nodes regarding route blinding:

- good progress has been made, nothing major to report
- minor issues are being worked on in https://github.com/ElementsProject/lightning/issues/5823
