### ISSUE TITLE
Lightning Specification Meeting 2023/01/16

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1050]
The meeting will take place on Monday 2023/01/16 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Clarify `channel_reestablish` requirements #1049 or #1051
- [x] Dual funding #851
- [x] Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22
- [x] Route blinding #765
- [x] Onion messages #759
- [x] Offers #798
- [x] Fat errors #1044
- [x] Add dust exposure threshold #919
- [x] Anchor outputs zero fee htlc txs test vectors #1018

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [x] Taproot #995
- [ ] ~Closing fee range turn-based protocol #1016~
- [ ] ~Update static channel parameters #1026~
- [ ] ~Sign commitments at various feerates #1036~
- [ ] ~Liquidity ads #878~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Fix channel pruning behavior -> fixed in eclair, lnd was already fixed, what about ldk and cln?~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~
- [ ] ~Graph dump on `gossip_timestamp_filter` #980~
- [ ] ~Websocket transport #891~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Channel jamming #1043~
- [ ] ~Pinning attacks as related to splicing / dynamic commitments: https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-August/003665.html~
- [ ] ~Quiescence #869~
- [ ] ~Splicing #863~
- [ ] ~Simplified commitment #867~
- [ ] ~Hold htlcs before forwarding #989~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Peer storage backup #881~
- [ ] ~Anonymous gossip~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by Roasbeef** [comment]
chan reest scenario:
  * lnd has a temporary work around, can just start to send the error the very first time
  * CLN also working on fixing some things in their flow as well, they recently added a similar recovery flow
      * will also have a grace period before they force close
   * t-bast working on a bigger refactoring of the entire section, in an attempt to make the entire section clearer 

dual funding:
* some small changes, added recently:
     * Lisa's suggestion that when you send a tx abort, the peer that received it should echo it back 
     * also makes it easier to know when one is leaving STFU mode 
  * related to ensuring stuff like cancelling RBFs work more reliably 
* matt morehouse making more progress for lnd
* CLN progress: new PR up, tests there mostly working, changed some aspects w.r.t `accept_channel2`, etc
* LDK progress: existing contributor picking up, still pretty early 

inbound fees:
  * another instance now by telling you peer to increase/decrease _their_ fees
  * some suspect won't be as popular as ppl think it will be: we've given them a new knob, but how well will it work out in practice? 
    * how popular will it actually become if ppl just do the experiment? 
   * difference in the deployment horizon as well
     * p2p: need all your channel peers to update
     * gossip: only need the sender to update 

route blinding:
  * CLN and Eclair doing direct interop, working on fixing some of the interactions 
  * lnd has a few PRs up now, targeting 0.17 (the next next release, last was 0.15.5), focusing on getting the forwarding logic pinned down first 
     * also able to send/recv now with some lnd works? 
     * PR now up to allow nodes to _pay_ blinded routes, need to work out some final kinks 

offers:
  * CLN modified version in latest release, broke recently, now focusing on more interop 

fat errors:
  * not much happened since then
  * ppl now interested in being able to signal the structure of the error (max number of hops, max size in payload) 
     * or if you use `diameter + 1`, you're not really leaking anything? diameter seems to be about 7 or so in the network today
     * would make it more flexible generally 
  * number of dimensions: number of hops, and the length of the payload -- they need to sign over a set of possible message lengths 


taproot:
  * secp-zkp now working on v1.0.0 support!! https://github.com/ElementsProject/secp256k1-zkp/pull/211
  * LDK and lnd now pretty close to doing interop, new PR up against: https://github.com/Roasbeef/lightning-rfc/pull/5
  * lnd trying out a way to not have to write local secret nonce to disk:
     * using the existing shachain state to derive the nonce (no extra state)
  * change to co-op close flow:
     * responder just always accept w/e the initiator says 
     * degenerate case of: fee rate too low (can also force close there), so should at least recognize the range 
     * should at least observe the low end of the range, want to make sure it's able to get in the mempool
