### ISSUE TITLE
  Lightning Specification Meeting 2023/02/27

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1057]
The meeting will take place on Monday 2023/02/27 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Dual funding #851
- [x] Route blinding #765
- [x] Onion messages #759
- [x] Offers #798
- [x] Taproot #995
- [x] Fat errors #1044
- [x] Add dust exposure threshold #919
- [x] Splicing #863
- [x] Anchor outputs zero fee htlc txs test vectors #1018 and #1056
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~
- [ ] ~Closing fee range turn-based protocol #1016~
- [ ] ~Update static channel parameters #1026~
- [ ] ~Liquidity ads #878~
- [ ] ~Sign commitments at various feerates #1036~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Don't force close until error is received after `channel_reestablish` #934~
- [ ] ~Websocket transport #891~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [x] Channel jamming #1043 #1052
- [ ] ~Pinning attacks as related to splicing / dynamic commitments: https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-August/003665.html~
- [ ] ~Quiescence #869~
- [ ] ~Simplified commitment #867~
- [ ] ~Hold htlcs before forwarding #989~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Peer storage backup #881~
- [ ] ~Anonymous gossip~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by Roasbeef** [comment]
route blinding:
  * lnd has interop now in a PR, not yet reviewed 
  * main PR has been squashed down, ppl to do final pass overs now

onion messaging:
  * nearly universal interop? 
  * questions re how ppl handle the state machine of the non-happy path:
    * fall back if someone critical on the route doesn't support
       * ideally direct connect from there then 
    * what about timeouts? 
       * not direct signal if you send and packets get dropped, or timedout, etc 
       * will need co properly test/control to ensure UX is up to par w/ other solutions 

fat errors:
  * there, in a holding pattern 
  * someone from eclair making prototype

splicing:
  * eclair working on splicing stuff, made a lot of progress
     * things get hairy when you combine this w/ zero conf....IYKYK (when you get there) 
  * msat rounding  
     * issue where one party needs to round up and the other needs to round down 
     * current protocol uses the delta in msat, which then needs to work out properly on chain, or you risk bleeding out a sat or two on chain 
  * can the msat issue be avoided by just not sending the final amount? 
     * just send the inputs+outputs and then let the rest be implicit 
     * or you just need to express the fee or fee rate
   * will continue to brainstorm what other issue might pop up, etc

taproot channels:
  * lnd working thru PR review, in a holding pattern re interop 
  * secp-zkp PR now approved: https://github.com/BlockstreamResearch/secp256k1-zkp/pull/211
     * others can be unblocked now re giving feedback re APIs, etc 

dyn commit
  * lnd wanting to revisit, as a way to upgrade ppl to taproot channels, and also maybe across versions if something changes in the future 
  * CL wanting to revisit as well, since wanting to move ppl over to zero fee anchors
     * also have something custom already for static remote key
  * revisiting question of the overlap with splicing
     * eventually splicing has a channel type on it
