### ISSUE TITLE
 Lightning Specification Meeting 2023/03/13

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1058]
The meeting will take place on Monday 2023/03/13 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [ ] Dual funding #851
- [ ] Route blinding #765
- [ ] Add dust exposure threshold #919
- [ ] Onion messages #759
- [ ] Offers #798
- [ ] Taproot #995
- [ ] Fat errors #1044
- [ ] Splicing #863
- [ ] Clarify `channel_reestablish` requirements #1049 or #1051
- [ ] Peer storage backup #881

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22
- [ ] Closing fee range turn-based protocol #1016
- [ ] Update static channel parameters #1026
- [ ] Liquidity ads #878
- [ ] Sign commitments at various feerates #1036

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] Don't force close until error is received after `channel_reestablish` #934
- [ ] Websocket transport #891

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] Channel jamming #1043 #1052
- [ ] Pinning attacks as related to splicing / dynamic commitments: https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-August/003665.html
- [ ] Quiescence #869
- [ ] Simplified commitment #867
- [ ] Hold htlcs before forwarding #989
- [ ] Trampoline routing #829 and #836
- [ ] Anonymous gossip
- [ ] lnprototest (https://github.com/rustyrussell/lnprototest)

**Comment by t-bast** [comment]
I won't be able to attend this spec meeting, I'll be traveling at that time. But I'm strongly ACK-ing dual funding and route blinding if you want to have a look at those!

**Comment by Roasbeef** [comment]
Won't be able to attend due to a conflict, so here're some updates on my end:
  * The last [PR in the taproot saga for lnd is up](https://github.com/lightningnetwork/lnd/pull/7472). This covers all the on-chain logic (HTLC redemption, breaches, second level handling, etc). From here on we'll be adding more unit and integration tests, to increase confidence in all the new code. 
      * I need to update the spec in response to comments, and also add in those script changes mentioned a few meetings ago (my PR above was pinned to the spec snapshot so I could have a static target). 
       * We're still in a waiting-for-interop holding pattern. 
   * We've started to explore the design space for "Gossip 1.5" (gateway drug to PLTCs, needed so taproot chans can be advertised. @ellemouton has posted a public spec draft here: https://github.com/ellemouton/bolts/pull/2/files -- mostly in place, but a few open questions and other things to be filled in. 
       * The most immediate effect here is that we need yet-another-set-of-nonces to be able to sign the `announcement_signatures_2` message. Open question here is: where should we piggy back this? In the normal chan open message, or later in `funding_locked/chanel_ready`?
   * We've done more exploration re a dynamic commitments carve out to aide in upgrade to taproot chans, but no concrete updates here beyond the existing draft spec PR (tho that only does params like `max_htlc` and needs to be updated to handle the new off-chain layer of indirection to go from segwit v0 to v1).

**Comment by carlaKC** [comment]
Transcript: https://github.com/bitcointranscripts/bitcointranscripts/pull/236
