### ISSUE TITLE
Lightning Specification Meeting 2023/04/24

### ISSUE THREAD

**Issue by Roasbeef** [lightning/bolts#1067]
The meeting will take place on Monday 2023/04/10 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Correct final CLTV for blinded paths: https://github.com/lightning/bolts/pull/1066
- [x] Onion messages #759
- [x] Offers #798
- [x] Add dust exposure threshold #919
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] Dual funding #851 (https://github.com/niftynei/lightning-rfc/pull/13 and https://github.com/niftynei/lightning-rfc/pull/15)
- [x] Splicing #863
- [x] Fat errors #1044
- [x] Clarify `channel_reestablish` requirements #1049 or #1051
- [x] Peer storage backup #881

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [x] Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22
- [ ] Closing fee range turn-based protocol #1016
- [ ] ~Update static channel parameters #1026
- [ ] Liquidity ads #878
- [ ] Sign commitments at various feerates #1036

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] Don't force close until error is received after `channel_reestablish` #934
- [ ] Websocket transport #891

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] Channel jamming #1043 #1052
- [ ] Pinning attacks as related to splicing / dynamic commitments: https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-August/003665.html
- [ ] Quiescence #869
- [ ] Simplified commitment #867
- [ ] Hold htlcs before forwarding #989
- [ ] Trampoline routing #829 and #836
- [ ] Anonymous gossip
- [ ] lnprototest (https://github.com/rustyrussell/lnprototest)

**Comment by Roasbeef** [comment]
blinded paths final CLTV delta:
  * Don't have a final CLTV delta, as you only have the full blinded path 
     * Since the receiver is the only that constructs the latter part of the route 
   * If you add any random values, then have to tell the recipient
   * Max cltv expiry was meant to be in the invoice, but seems to not actually be there anymore 
      * Goal to catch up the spec to implementations cc @t-bast @rustyrussell 

onion messaging:
  * test vectors updated, now rebased on top of blinded paths

offers:
  * now also rebased, implementations converging 
  * LDK a little bit away from interop testing, need to finalize the data structures, and also need the ability to generate blinded paths 

`max_dust_htlc_exposure_msat` addition:
  * need review from other implementations, acinq ACKd

taproot:
 * anchor output, tradeoffs re allowing 3rd parties to sweep 
    * the internal key they need to make a control block may not always be revealed 
    * modifying the to_local to have the revocation path in the script path 
    * before: can be swept after 16 block
    * now: can be swept after 16 blocks, and the local party has swept 
    * possible to add more information in the gossip to make it always sweepable 
    * another path:
       * make the witness slightly larger, by moving the revocation
  * which key is used for the to_remote party's internal output
     * realized that nice for back up + recovery 

taproot chans:
  * implications of block height based rate limiting
     * gossip query implications 
     * rate limiting re burst 
   * TLV everywhere or not
      * can be useful for revealing all the information w.r.t bitcoin script outputs
   * how much should be bound in the output:
      * how much the output script be bound?
      * how much the value should be bound?

attributable errors: 
  * is this compatible with blinded paths? does it require any additional changes to be compose? 
  * shouldn't be a problem? 
     * as just dropped from the introduction points, as then you want to make sure that you don't unnecessarily penalize for dropping  the hmacs 

peer channel backups:
  * CLN had an intern do node uploads for backup data 
  * old eclair version as well 
  * open work here to see if both can be combined or not

inbound fees: 
  * lnd looking at including in upcoming release 
  * implications re negative fees and if one can rely on other peers to send `channel_updates`
  * other peer level proposal updated
     * now factors in a time to wait before the peer starts to properly enforce the fee update

**Comment by carlaKC** [comment]
transcript: https://github.com/bitcointranscripts/bitcointranscripts/pull/261
