### ISSUE TITLE
Lightning Specification Meeting 2023/06/19

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1088]
The meeting will take place on Monday 2023/06/19 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [ ] ~Bolt 8 chaining keys clarification #1079~
- [ ] ~Correct final CLTV for blinded paths: #1066 and #1069~
- [ ] ~Harmonize max `cltv_expiry` across implementations #1086~
- [x] Fat errors #1044
- [ ] ~Onion messages #759~
- [x] Offers #798
- [ ] ~Add dust exposure threshold #919~
- [ ] ~Taproot #995~
- [ ] ~Taproot gossip #1059~
- [ ] ~Quiescence #869~
- [ ] ~Splicing #863~
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~
- [ ] ~Closing fee range turn-based protocol #1016~
- [x] Update static channel parameters #1026
- [ ] ~Liquidity ads #878~
- [ ] ~Sign commitments at various feerates #1036~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Dual funding #851~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~
- [ ] ~Websocket transport #891 or #1068~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Channel jamming #1043 #1052 #1071~
- [ ] ~Pinning attacks as related to splicing / dynamic commitments: https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-August/003665.html~
- [ ] ~Simplified commitment #867~
- [ ] ~Peer storage backup #881~
- [ ] ~Hold htlcs before forwarding #989~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Anonymous gossip~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by joostjager** [comment]
For attributable errors, the idea came up to reduce the number of bits in the hmacs to make the failure message smaller: https://github.com/lightningnetwork/lightning-onion/pull/60#pullrequestreview-1465324550

Interested to hear what people think of this.

**Comment by carlaKC** [comment]
I'd like to chat about a [loose structure](https://github.com/lightning/bolts/issues/1078#issuecomment-1593131854) for the upcoming summit based on [interest in various topics](https://github.com/lightning/bolts/issues/1078#issuecomment-1593114931).

**Comment by carlaKC** [comment]
Finally catching up on transcripts! https://github.com/bitcointranscripts/bitcointranscripts/pull/257

**Comment by Roasbeef** [comment]
My unofficial spec meeting topic study guide based on the now abandoned daily split: https://docs.google.com/document/d/1tU9AqbCWf_rdl7gJAWN18oDFhTk_yQt8mEb3vz_F8Ls/edit?usp=sharing
