### ISSUE TITLE
Lightning Specification Meeting 2023/07/31

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1098]
The meeting will take place on Monday 2023/07/31 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Simplified mutual close #1096
- [x] Clarify behavior when both optional and mandatory feature bits are set #1095
- [x] Spec clean-up #1092
- [x] Correct final CLTV for blinded paths: #1097 and #1069
- [x] Harmonize max `cltv_expiry` across implementations #1086
- [x] Attributable errors #1044
- [x] Onion messages #759
- [x] Offers #798
- [x] Add dust exposure threshold #919
- [x] Taproot #995
- [ ] Taproot gossip #1059
- [ ] Quiescence #869
- [ ] Splicing #863 vs Dynamic Commitments #1090
- [ ] Clarify `channel_reestablish` requirements #1049 or #1051

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22
- [ ] Liquidity ads #878
- [ ] Sign commitments at various feerates #1036

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] Dual funding #851
- [ ] Don't force close until error is received after `channel_reestablish` #934
- [ ] Websocket transport #891 or #1068

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] Channel jamming #1043 #1052 #1071
- [ ] Simplified commitment #867
- [ ] Peer storage backup #881
- [ ] Hold htlcs before forwarding #989
- [ ] Trampoline routing #829 and #836
- [ ] Anonymous gossip
- [ ] lnprototest (https://github.com/rustyrussell/lnprototest)

**Comment by t-bast** [comment]
I won't be available for this spec meeting either (yay french holidays) but I'll review most PRs before that!

**Comment by jkczyz** [comment]
I drafted a small PR (#1099 based on #798) to allow using scids in an offer's blinded path, as discussed last meeting.

**Comment by Roasbeef** [comment]
simple close chans:
  * will people implement this before or after taproot channels? 
  * how do we want to handle the feature gating here?
     * as is, it just assumes this is the "thing" and doesn't have any feature bit negotiation
     * in the form of two commits: adds it all, then removes the old
        * gives people an option w.r.t what they want
           * should it be the only way for taproot? 
  * shutdown retransmission:
     * if you reconnect, then you can send shut down again 
     * will always start with the shutdown sequence with the nonce
  * what to do if no one cares about their output?
     * allows either party to omit their own? or only if it's higher 
     * what about the dust values? 
   * game theory? 
      * paying for own thing, so want you to pay vs not 
      * normal case, opener is paying all the fees 
      * what if you really don't want to pay?
          * propose fee that's below 1 sat/byte, or a zero fee close 
          * then you sign off 
          * but already the same with the current force close hijinks? 
        * doesn't the existing dust field allow us to figure things out?
        * diff is you know exactly how much it'll cost to spend it 
           * so then ends up being a way to late bind the dust values 
   * op_return 
       * allow both sides to just say they don't want the channel 
       * in practice, just close on min fee and let propagate, this is the nuclear scenario where don't care about


optional + require bits:
  * undefined what to do if someone sets both 
  * people seem to not care about it rn? maybe in the future we can pick an interpretation for it?


cleaning up features:
  * perhaps we just make a jump to required first? then revisit afterwards
  * then later on can set the new assumption behavior

attributable errors:
  * have clearer scope, looking to reduce the hmac size 
  * needs spec updates, lnd impl to be updated, then waiting for interop w/ the rest

onion messaging:
  * has interop, working on more interop
  * LDK working on test vectors

offers:
  * needs test vectors

dust exposure:
  * rusty promises that he'll review it today

taproot:
  * FROST questions re nested musig vs not

**Comment by carlaKC** [comment]
Trasncript: https://github.com/bitcointranscripts/bitcointranscripts/pull/270

**Comment by t-bast** [comment]
> simple close chans:
>    - will people implement this before or after taproot channels?

On the eclair side, we will implement this soon, much before taproot channels, this way we can pave the road for deprecation of the older closing protocols.
