### ISSUE TITLE
Lightning Specification Meeting 2023/08/28

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1103]
The meeting will take place on Monday 2023/08/28 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Harmonize max `cltv_expiry` across implementations #1086
- [x] Simplified mutual close #1096
- [x] Spec clean-up #1092
- [x] Use scid in blinded paths #1099
- [x] Offers #798
- [x] Quiescence #869
- [x] Splicing #863 vs Dynamic Commitments #1090
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] Attributable errors #1044
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~
- [ ] ~Liquidity ads #878~
- [ ] ~Sign commitments at various feerates #1036~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Dual funding #851~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~
- [ ] ~Websocket transport #891 or #1068~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Channel jamming #1043 #1052 #1071~
- [x] Simplified commitment #867
- [ ] ~Peer storage backup #881~
- [ ] ~Hold htlcs before forwarding #989~
- [ ] ~Trampoline routing #829 and #836~
- [x] lnprototest (https://github.com/rustyrussell/lnprototest)

**Comment by ariard** [comment]
If there is enough compatibility testing between 2 implementations on #851, maybe it could be marked as finalized or landed. I think this is kinda a blocker to review / implement #863 as it unclear if it strictly building on it.

**Comment by t-bast** [comment]
> If there is enough compatibility testing between 2 implementations on https://github.com/lightning/bolts/pull/851, maybe it could be marked as finalized or landed.

We're getting close, but we're still missing interop tests on the `channel_reestablish` part. @niftynei is working on finalizing those on `cln`. Once those tests are done, we can do a final rebase of that PR and merge it :rocket:

**Comment by carlaKC** [comment]
Transcript: https://github.com/bitcointranscripts/bitcointranscripts/pull/275
