### ISSUE TITLE
  Lightning Specification Meeting 2023/09/11

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1107]
The meeting will take place on Monday 2023/09/11 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Set `dont_forward` bit on initial `channel_update` (before 6 confs) #1106
- [x] Add replay-specific onion failure code #1105
- [x] Harmonize max `cltv_expiry` across implementations #1086
- [x] Simplified mutual close #1096
- [x] Spec clean-up #1092
- [x] Use scid in blinded paths #1099
- [x] Offers #798
- [x] Quiescence #869
- [x] Splicing #863 vs Dynamic Commitments #1090
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] Attributable errors #1044
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~
- [ ] ~Liquidity ads #878~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [x] Dual funding #851
- [x] Don't force close until error is received after `channel_reestablish` #934
- [ ] ~Websocket transport #891 or #1068~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [x] Channel jamming #1043 #1071
- [x] Simplified commitment #867
- [x] Peer storage backup #881
- [ ] ~Hold htlcs before forwarding #989~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by Crypt-iQ** [comment]
Was there an update on #1105 ?

**Comment by carlaKC** [comment]
> Was there an update on #1105 ?

Probably not going to be helpful in the event of an _actual_ replay attack because the intermediate node doing it will just trash the error, _but_ useful for debugging accidental replay so go ahead with a PR 👍

**Comment by carlaKC** [comment]
Jitsi borked out on me while I was recording this one and dropped me from the call (which killed the recording without downloading) so we're going to be without a transcript for this one :(
