### ISSUE TITLE
 Lightning Specification Meeting 2023/09/25

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1114]
The meeting will take place on Monday 2023/09/25 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Experimental feature bit recommendation #1108
- [x] Clarify `offered` and `negotiated` features #1109
- [x] Clarify `max_htlc_value_in_flight_msat` #1113
- [x] Harmonize max `cltv_expiry` across implementations #1086
- [x] Simplified mutual close #1096
- [x] Spec clean-up #1092
- [x] Offers #798
- [x] Quiescence #869
- [x] Splicing #863 vs Dynamic Commitments #1090 vs Upgrade on reestablish #868
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] Attributable errors #1044
- [x] Clarify `channel_reestablish` requirements #1049 or #1051

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~
- [ ] ~Liquidity ads #878~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Dual funding #851~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~
- [ ] ~Websocket transport #891 or #1068~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Channel jamming #1043 #1071~
- [ ] ~Simplified commitment #867~
- [ ] ~Peer storage backup #881 or #1110~
- [ ] ~Hold htlcs before forwarding #989~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by t-bast** [comment]
I won't be able to attend this meeting, but I'll review most PRs before that. I started working on `option_simple_close` in https://github.com/ACINQ/eclair/pull/2747 which means I have a lot of feedback on that one!

**Comment by Roasbeef** [comment]
simplified close:
  * lots of initial review by t-bast, few iterations, now enshrines the dust rule amongst other things
  * now working on getting an initial implementation going 
  * roasbeef still has on his list to take a look at, and also start with a basic implementation 


clean up feature bits:
  * want to start to make compulsory first, then later on see if we can start to ignore them 
  * CLN starting to make all the features compulsory, will do for next release (winter-ish) 
 

CLN anchor inflight upgrade:
 * using old method used to upgrade, uses the `stfu` message now 
 * uses a TLV in the `chan_reest` message, says to upgrade chan then goes from there 
    * assumes having nothing to retransmit 
 * can also use `stfu` to force if needed, "special" case of a no param update, so nothing else that needs to be sent 

`stfu` message:
  * needed for splicing, dyn commits and all other stuff
  * may have identified an edge case where the channel actually never fully clears out 
  * rusty to take a look at the edge case, see what type of rework is needed 

taproot:
  * LDK waiting on next release, then can pick back up 
  * gossip work to pick back up in the next week or two

**Comment by carlaKC** [comment]
Transcript: https://github.com/bitcointranscripts/bitcointranscripts/pull/282
