### ISSUE TITLE
Lightning Specification Meeting 2023/10/09

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1115]
The meeting will take place on Monday 2023/10/09 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [ ] Clarify `offered` and `negotiated` features #1109
- [ ] Harmonize max `cltv_expiry` across implementations #1086
- [ ] Simplified mutual close #1096
- [ ] Spec clean-up #1092
- [ ] Offers #798
- [ ] Quiescence #869
- [ ] Splicing #863 vs Dynamic Commitments #1090 vs Upgrade on reestablish #868
- [ ] Taproot #995
- [ ] Taproot gossip #1059
- [ ] Attributable errors #1044
- [ ] Clarify `channel_reestablish` requirements #1049 or #1051

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22
- [ ] Liquidity ads #878

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] Dual funding #851
- [ ] Don't force close until error is received after `channel_reestablish` #934
- [ ] Websocket transport #891 or #1068

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] Channel jamming #1043 #1071
- [ ] Simplified commitment #867
- [ ] Peer storage backup #881 or #1110
- [ ] Hold htlcs before forwarding #989
- [ ] Trampoline routing #829 and #836
- [ ] lnprototest (https://github.com/rustyrussell/lnprototest)

**Comment by t-bast** [comment]
We're entering the daylight savings time changes mess, I'm not 100% sure I put the right time, be ready for last minute changes!

**Comment by Roasbeef** [comment]
feature bit checks:
 * intent to make more lenient on the sender side of things: https://github.com/lightning/bolts/pull/1109

new co-op close:
   * want to leave off last commit where we remove 
   * lnd implements the RBF signalling, but plans to upgrade w/ the new feature bit 
       * staging bit just signals RBF, final version will also assume the new co-op close
   * moves to get more introp, eclair ready ready for interop

cleaning up features w/ required bit
    * lnd prepped to add in lnd 0.18 
    * eclair has in master branch, to go out this week or the next

offers:
   * LDK next release will have a basic version, needs direct connect 
   * eclair ready to test scid encoding variant with other impls too

splicing:
  * dusty still handling the PR rn 
      * working on restart related nuances on the implementation side of things 
      * according to t-bast a lot of cases re the restart stuff, based on TLVs in the chan reest message
  * CLN continuing to test, running into some fun edge cases 

dual funding cross compat
   * need some final stuff, related to restarting that needs interactive-tx, one sides sends commit sig + tx sig
      * need to make sure able to finish the signing session 
    * lisa working on final fixes here

taproot:
  * splicing nonces for taproot chans, can use the same ordering
      * if don't want explicit ordering, then have the splice ordering of the transactions, order the nonces 
      * explicit: would map splice tx to nonces
   * miniscript analysis run: https://github.com/lightning/bolts/pull/995#issuecomment-1754696676 
       * need to double check the scripts side by side, looses a byte here n there 

gossip 1.5:
  * thinking about how to support the backwards compat
      * segwit v0 channels to announce the new gossip 1.75 messages, chanupd2, ann2
      * do we also support the queries with block timestamp and block height
         * possible to map one to another, dev wisdom says harder in practice w/ edge cases n stuff 
      * also path to just do minisketch instead, so then all block heights

attributable errors:
  * ready to do interop w/ joost

zero chan reserve:
  * want to be set to zero, to allow setting it 
  * even if set to zero, then you still need to fee to pay for the tx
     * not zero, but instead it's min to pay for fees (as initiator?) 
   * how is this diff from zero conf?
      * zero conf is transient, this is for the lifetime of the channel

**Comment by carlaKC** [comment]
transcript: https://github.com/bitcointranscripts/bitcointranscripts/pull/293
