### ISSUE TITLE
 Lightning Specification Meeting 2023/11/06

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1116]
The meeting will take place on Monday 2023/11/06 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Dual funding #851
- [x] Simplified mutual close #1096
- [x] Peer storage #1110 
- [x] Spec clean-up #1092
- [x] Offers #798
- [x] Quiescence #869
- [x] Splicing #863 vs Dynamic Commitments #1090 vs Upgrade on reestablish #868
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] Attributable errors #1044
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~
- [x] Liquidity ads #878

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Don't force close until error is received after `channel_reestablish` #934~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Channel jamming #1043 #1071~
- [ ] ~Simplified commitment #867~
- [x] Peer storage backup #881 or #1110
- [ ] ~Hold htlcs before forwarding #989~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by niftynei** [comment]
liquidity ads: 
- @niftynei is updating the existing spec PR (#878); anticipated changes: use CLTV not CSV; 
- rationale for CLTV: the liquidity buyer is incentivized to mine the channel tx ASAP to receive their liquidity, so it's fine if the time to mine takes a while as it counts against their own guaranteed liquidity purchase
- @Roasbeef is going to send notes on the existing CLTV protocol changes they've made for an existing LND channel-type
- no preference on BLIP vs BOLT; @niftynei to continue with updating existing BOLT PR
- fraud proofs: existing liquidity ads spec contains them for agreed channel fees; @niftynei + @t-bast to confirm that the alias PR (?) works with this

**Comment by joostjager** [comment]
Regarding attr errors:
>if the onion isn't useable, what do you do?

https://github.com/lightningnetwork/lnd/pull/7139/commits/f942e03dfaf520054914b22da8cdc7dbad605d8d#r1383964003

**Comment by carlaKC** [comment]
Transcript: https://github.com/bitcointranscripts/bitcointranscripts/pull/311
