### ISSUE TITLE
Lightning Specification Meeting 2023/11/20

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1118]
The meeting will take place on Monday 2023/11/20 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Special topics

- [ ] Mailing list host ending support in 2023

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [ ] Dual funding #851
- [ ] Liquidity ads #878
- [ ] Simplified mutual close #1096
- [ ] Spec clean-up #1092
- [ ] Offers #798
- [ ] Quiescence #869
- [ ] Splicing #863 vs Dynamic Commitments #1090 #1117 vs Upgrade on reestablish #868
- [ ] Taproot #995
- [ ] Taproot gossip #1059
- [ ] Attributable errors #1044
- [ ] Clarify `channel_reestablish` requirements #1049 or #1051
- [ ] Channel jamming #1043 #1071
- [ ] Peer storage backup #881 or #1110

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] Don't force close until error is received after `channel_reestablish` #934

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] Simplified commitment #867
- [ ] Hold htlcs before forwarding #989
- [ ] Trampoline routing #829 and #836
- [ ] lnprototest (https://github.com/rustyrussell/lnprototest)

**Comment by carlaKC** [comment]
I'd like to talk about https://github.com/lightning/blips/pull/27, specifically the possibility of various implementations: 
1. Relaying experimental endorsement signal (just propagating the incoming value received to the outbound link)
2. Setting experimental endorsement = 1 as the sender (with some probability P)

**Comment by t-bast** [comment]
Perfect, I wanted to talk about that too, since we have a PR ready on the eclair side and were wondering if it was worth integrating and deploying it.

**Comment by Roasbeef** [comment]
mailing list stuff:
   * what are we gonna do? 
   * EOY deadline
   * is the software that hard to run? 
   * options:
      * google groups 
         * can you subscribe w/o a gmail account? 
      * github discussions 
      * linux foundation-like mailing list 
      * discourse (delving bitcoin)
   * should we try to do google groups?
 
dual funding:
 * minor comments, lisa pushed up new version, last call for review 
 * last changes was just white space mainly

liquidity ads:
  * lisa sent out ML post
  * new version up, in draft, not fully implemented 
  * main changes:
     * used CSV, now moving to CLTV 
     * prior version had fixed size (4k blocks), new proposal lets you control to which block you want the lease to end 
  * thinking thru some stuff with the CLTV change and HTLCs:
     * party selling can still get the other to force close to 
     * solution could be to limit the the `max_in_flight` value, so limits the amt that can be leaked from the channel 

new simple close:
  * eclair has an impl, waiting for interop 
  * lnd working on impl, shooting to have up by next spec meeting 

spec required feature bits
   * nothing new, some have it in master already

bolt 12 LN addr ML post:
  * idea is to remove the IP leaks w/ the current LN addr protocol 
  * for BOLT 12 just need the ability to fetch the offer, as the offer can be used to fetch new invoices 
  * can use DNS to make it better, either:
     * 1 DNS entry per user for the offer, could be annoying from an ops PoV 
         * directly map from DNS to user 
     * do DNS to map a domain to a node ID
         * don't do a node ID, but it returns a blinded path
         * payer contacts node, to then redirect to final user to get a BOLT 12 offer from the user
         * ultimately TOFU, sig attests that things are correct
  * even if using custodial or non-custodial service, you can take that and put it in your DNS
  * could also just do pure DNSSEC:
     * bootstrapped, but then node ann has a cert that includes the node pubkey, so attestation on the TLS level

channel jamming
  * simulations on going 
  * thinking about feasibility of doing initial deployment on mainnet
     * are we ok relaying even if not implementing any of it?
     * are we ok w/ setting the value w/ x% of payments
  * should we have a flag day re starting to set it and also starting to set it on relay?
     * ppl seem generally ok with it, can give away some information 
  * end goal:
      * if ppl start to relay it, then we can actually start running the proper experiments 
      * ppl will relay the value, so others can start to set it 


stfu/quiescence:
  * lnd starting to implement, figuring out the pipeline thru the code

taproot chans + gossip:
   * lnd has script changes staged, need to push out along w/  test vectors
   * LDK rebasing, planning taproot stuff for release 119 

attributable errors:
  * joost working thru changes + updates 
  * maybe move the bit into the update add HTLC

**Comment by carlaKC** [comment]
Transcript: https://github.com/bitcointranscripts/bitcointranscripts/pull/346
