### ISSUE TITLE
Lightning Specification Meeting 2023/12/18

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1124]
⚠️ **This meeting will be skipped, go enjoy your holidays folks, get away from that keyboard for a few days!** ⚠️

The meeting will take place on Monday 2023/12/18 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Special topics

- [ ] Final call for mailing list host ending support in 2023

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [ ] Dual funding #851
- [ ] Liquidity ads #878
- [ ] Simplified mutual close #1096
- [ ] Quiescence #869
- [ ] Trampoline routing #829 and #836 (2024 is going to be the year of trampoline :tada:)
- [ ] Spec clean-up #1092
- [ ] Offers #798
- [ ] Taproot #995
- [ ] Taproot gossip #1059
- [ ] Attributable errors #1044
- [ ] Channel jamming #1043 #1071
- [ ] Splicing #863 vs Dynamic Commitments #1090 #1117 vs Upgrade on reestablish #868
- [ ] Clarify `channel_reestablish` requirements #1049 or #1051
- [ ] Peer storage backup #881 or #1110

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] Don't force close until error is received after `channel_reestablish` #934

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] Simplified commitment #867
- [ ] Hold htlcs before forwarding #989
- [ ] lnprototest (https://github.com/rustyrussell/lnprototest)

**Comment by t-bast** [comment]
Works for me, Rusty said he would be on vacation as well, let's do sync in early January then!

**Comment by morehouse** [comment]
> Works for me, Rusty said he would be on vacation as well, let's do sync in early January then!

Do we have a final plan for the mailing list?  IIRC, it will go away at EOY, and it seems we might not have a replacement before then.

**Comment by t-bast** [comment]
> Do we have a final plan for the mailing list? IIRC, it will go away at EOY, and it seems we might not have a replacement before then.

We can discuss that directly here I guess? I personally played around a bit more on delvingbitcoin and configured notifications, I'm happy with it, but I'd be happy with a standard mailing list as well. I haven't tried the discourse backup feature yet, I think that's one important thing to check.

**Comment by vincenzopalazzo** [comment]
I am fine with Delving Bitcoin but let keep the conversation in a single place, so when we move to Delving Bitcoin we should deprecate the list or something like that.

Otherwise it is hard to keep up with everything

**Comment by t-bast** [comment]
I'm fine with either choice (discourse or standard ML), so I'll also let others who feel more strongly decide!

**Comment by ariard** [comment]
Can be pinned: https://github.com/lightning/bolts/issues/1126
