### ISSUE TITLE
 Lightning Specification Meeting 2024/01/29

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1129]
The meeting will take place on Monday 2024/01/29 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Dual funding #851
- [x] Simplified mutual close #1096 
- [x] Trampoline routing #829 and #836 (2024 is going to be the year of trampoline :tada:)
- [x] Channel jamming #1043 #1071 https://github.com/lightning/blips/pull/27
- [x] Liquidity ads #878
- [ ] ~Quiescence #869~
- [ ] ~Offers #798~
- [ ] ~Taproot #995~
- [ ] ~Taproot gossip #1059~
- [ ] ~Attributable errors #1044~
- [ ] ~Splicing #863 vs Dynamic Commitments #1117 vs Upgrade on reestablish #868~
- [ ] ~Peer storage backup #881 or #1110~
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Spec clean-up #1092~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Simplified commitment #867~
- [ ] ~Hold htlcs before forwarding #989~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by carlaKC** [comment]
Bumping from last meeting: https://github.com/lightning/blips/pull/27

**Comment by Roasbeef** [comment]
dual funding:
  * forces you to provide the whole prev transaction for the input
     * issue in practice as means restricted to 65 KB
     * if trying to bring funds into a channel or mining pay out, etc 
     * proposal: get rid of this
     * alternative: paper around the 65 KB limit w/ application level chunking or transport level chunking 
     * why do we need this at all?
        * case where there's a mixed input in a unconfirmed transaction, it can modify the tx?
        * unclear how it can be exploited in the first place
        * **all the inputs of unconfirmed transaction as input to funding tx need to be pure segwit** 

rbf-coop close:
  * in bitcoind 25, `OP_RETURN` must now have a zero value output 
  * interaction with the older version?
      * single funder, all funds on the side of Bob, 
  * altruistic version:
     * you can't pay for fees, but you send `closing_complete`, then send `no_closer_closee`
  * lnd close to do interop with eclair, CLN has next release, then working to make concrete 

trampoline:
  * chat last time about modifying the onion construct: prefix, or onion within the onion 
  * have implemented relaying to a blinded path 
  * arik fine with keeping as is, working thru impl

channel jamming
   * do we have a feature bit?
     * can only start setting as the sender once more of the network has been updated
     * can use a high feature bit for now 
     * yes: should make a PR to the BOLTs to specify a feature bit
   * experiment:
     * learning circuit breaker along side, able to drop the rep down to zero based on w/e azlgo 
     * collect the signals the be able to dry run the rep on mainnet

**Comment by t-bast** [comment]
> why do we need this at all?
>    - case where there's a mixed input in a unconfirmed transaction, it can modify the tx?
>    - unclear how it can be exploited in the first place
>    - all the inputs of unconfirmed transaction as input to funding tx need to be pure segwit

I've figured out the details, and explained them here: https://delvingbitcoin.org/t/malleability-issues-when-creating-shared-transactions-with-segwit-v0/497

That means we cannot simply drop the `prevtx` field from `tx_add_input` messages that claim to use taproot, because that could be a lie. We can only allow the other participant to omit the `prevtx` field from their `tx_add_input` messages if we know we will include a taproot input on our side, which will commit to the `scriptPubKey`s our peer claims to use.

**Comment by ariard** [comment]
> channel jamming

have the credentials in its own embedded rust lib, working poc: https://github.com/ariard/staking-credentials
works well for 1-to-1 coverage of liquidity usage (1sat of liquidity covered by 1sat of pre-paid token).
