### ISSUE TITLE
Lightning Specification Meeting 2024/03/11

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1146]
The meeting will take place on Monday 2024/03/11 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Zero reserve #1140 (follow-up on #1133 to include a feature bit) 
- [x] Trampoline routing #829 and #836
- [x] Simplified mutual close #1096
- [x] Allow `sciddir_or_pubkey` for every hop #1138
- [x] Liquidity ads #878 #1145
- [x] Quiescence #869
- [x] DNS-based offers #1136
- [x] Splicing #863 vs Dynamic Commitments #1117 vs Upgrade on reestablish #868
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] Peer storage backup #881 or #1110
- [x] Channel jamming #1043 #1071 https://github.com/lightning/blips/pull/27
- [x] Attributable errors #1044
- [x] Offers #798
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [x] Spec clean-up #1092
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Simplified commitment #867~
- [ ] ~Hold htlcs before forwarding #989~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by carlaKC** [comment]
Transcript: https://github.com/bitcointranscripts/bitcointranscripts/pull/453
