### ISSUE TITLE
Lightning Specification Meeting 2024/04/08

### ISSUE THREAD

**Issue by Roasbeef** [lightning/bolts#1152]
The meeting will take place on Monday 2024/03/25 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

:warning: Some countries are switching to DST in the coming weeks, be careful with the meeting time!

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Spec clean-up #1092
- [x] Simplified mutual close #1096
- [x] Liquidity ads #878 #1145
- [x] Allow `sciddir_or_pubkey` for every hop #1138
- [x] Async payments #1149
- [x] Trampoline routing #829 and #836
- [x] Quiescence #869~
- [x] Splicing #863 vs Dynamic Commitments #1117 vs Upgrade on reestablish #868
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] Peer storage backup #881 or #1110
- [x] Channel jamming #1043 #1071 https://github.com/lightning/blips/pull/27
- [x] Offers #798
- [x] DNS-based offers #1136
- [x] Attributable errors #1044
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Zero reserve #1140 (follow-up on #1133 to include a feature bit)~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Simplified commitment #867~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by Roasbeef** [comment]
feature bit clean up:
  * moving back to optional for gossip queries 
  * PR to be updated 

rbf coop close:
  * lnd to update with the lock time change, then start interop with eclair 

liquidity ads:
  * PR now updated, has the additional details in the body, needs review 

trampoline:
  * LDK moving forward with serialization and parsing support, moving now into API and beyond 

stfu interop:
  * doing interop testing w/ lnd and eclair -- revealed a bug in the lnd impl, currently fixing 
  * lnd working on putting up a draft of the resume message, to detail all the semantics around if the messages arrive out of time
       * how do you handle the complexity on sending resume, then something else happens, all those edge cases 
       * similar-ish to what you'd already handle for random disconnect 

splicing:
   * dusty fleshing out his splicing DSL
   * spec progress:
      * big TODO list of things working thru, 8-12 items to get through: https://github.com/lightning/bolts/pull/863#issuecomment-1942739554
      * once those are through, then back to more interop to polish up the spec further

taproot & gossip:
  * eclair working on interop 
  * lnd on holding pattern w gossip changes 

peer back up:
   * lnd progressing w/ implementation, almost complete 

blinded paths:
  * lnd on final PR, error handling items, hoping to land into 0.18 (next major release) 
  * interop:
      * lnd <-> CLN: max CLTV height seems to be wrong, issue made in the CLN tracker for 

channel jamming:
  * bLIP now ready for people to take a look at
  * setting the bit now, questions of how many bytes should be allocated to the purpose 

offers:
  * scid pubkey is still there, now only for the introduction node 
  * LDK has PR to do parsing, then handling is up next 

inbound fees:
  * lnd merged in initial version, staged roll out, negative only (discounts to start with)

**Comment by carlaKC** [comment]
Transcript: https://github.com/bitcointranscripts/bitcointranscripts/pull/478
