### ISSUE TITLE
Lightning Specification Meeting 2024/04/22

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1155]
The meeting will take place on Monday 2024/04/22 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Spec clean-up #1092
- [x] Constant size failure onion decryption #1154
- [x] Notation for math content #1151
- [x] Liquidity ads #878 #1145 #1153
- [x] Async payments #1149
- [x] Quiescence #869
- [x] Splicing #863 vs Dynamic Commitments #1117 vs Upgrade on reestablish #868
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] Peer storage backup #881 or #1110
- [x] Channel jamming #1043 #1071 https://github.com/lightning/blips/pull/27
- [x] Offers #798
- [x] DNS-based offers #1136
- [ ] ~Attributable errors #1044~
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Simplified mutual close #1096~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Zero reserve #1140 (follow-up on #1133 to include a feature bit)~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Simplified commitment #867~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by t-bast** [comment]
I'll do my best, but I'm not there I'll be there in time for this meeting. In case I can't attend, here are some topics I'm waiting for feedback on:

- I think it's time to finalize #1092, and I've added a commit containing some clean-up (see https://github.com/lightning/bolts/pull/1092#pullrequestreview-2006373363)
- I've posted a new design for liquidity ads in #1153 that is more open to extension, and I believe would work great to unify LSP specs with the BOLTs and bLIPs, I'm chasing some concept ACK on this (@niftynei)
- In order to ship some prototype Bolt 12 implementation, we'd like to get rid of a requirement that unnecessarily duplicates the node key: https://github.com/lightning/bolts/pull/798#discussion_r1561194645 (@rustyrussell)
- it would be great to make progress on taproot gossip, we've all signaled willingness to ship it whenever possible

**Comment by Roasbeef** [comment]
feature bit clean up:
  * lnd will implement as is in 0.18, the rest have as well 
  * no blockers to landing, ppl should add their final approvals 

constant sized decryption:
  * does everyone actually do it?
     * seems so
  * PR also updates the 20 hop value to 27 (can be considered an independent bug fix) 
  * perhaps we should just make the section more generic? 
    * so advise randomization between payment retries, remove the prescriptive text rn re the exact method 
    * other areas:
       * fuzz latency responding to pings

LaTeX for blinded paths:
  * merged!
  * https://github.com/lightning/bolts/pull/1151

unified liquidity ads:
  * new PR, more extensible 
  * looking for concept ACK 

async payments:
  * still working on LDK updates, have some updates to feature bits, etc 

stfu:
   * keagan submitted a PR to rusty's branch attempting to add an explicit resume
      *  PR: https://github.com/rustyrussell/lightning-rfc/pull/14 
   * t-bast has replied to, fielding comments, now

splicing + dyn commits:
 * key distinction re funding output channel updates:
    * always broadcast the splicing/kick off 
    * keep it off chain as long as possible 
  * dyn commits as specified seeks to decouple negotiation from execution
     * can update dust limit etc w/o needing to change a funding output


taproot gossip + channels:
  * eclair working on interop w/ channels 
  * rusty left some initial comments based on the current revision: https://github.com/lightning/bolts/pull/1059#issuecomment-2048839371

peer backup:
  * impls underway 
  * spec PR getting some review now 

channel jamming:
   * was a hackathon at the MIT bitcoin conf
      * had ppl launch attacks, not totally broken, but have some new insight from it
       * will be a delving post summarizing 


offers:
  * idea to make the node ID implicit, can make the QR code smaller 
     * should it be done before or after we merge it in?
     * has been implemented in Phoenix, want to have the default, small change 
        * for certain apps, won't change for the foreseeable future 
     * may miss the LDK release deadline
   * can implement sending to it vs also understanding receiving to it
   * state of CLN implementation:
      * a bit behind the spec 
      * shooting to update it for next CLN release, sometime in May 
   * what does minimal interop here look like?
      * multi-hop fetch? dummy hops? direct connect?
   * expiry height issue to be addressed

DNS based offers:
  * waiting for more feedback

**Comment by t-bast** [comment]
> idea to make the node ID implicit, can make the QR code smaller
>    should it be done before or after we merge it in?

It must absolutely be done before merging, otherwise old readers won't know how to read offers that don't include this `offer_node_id`, it will require a `mandatory` feature bit, which is really wasteful. From the reader's point of view it's a trivial change, I think it belongs to the MVP.

**Comment by t-bast** [comment]
> It does not - old senders will simply fail to read the QR, same behavior whether its a feature bit or not :).

Right, but that's really not the UX we want to have for the first wave of Bolt 12 adopters! It would be really sad to have cross-compatibility issues like those right from the start.

> Fair, but sadly LDK is gonna ship a new release without this and we anticipate pushing some of our larger users to integrate BOLT12 using this release. Of course that doesn't mean all that much, but it may mean that people start supporting BOLT12-send in production without this feature for a month or three.

That means omitting the `offer_node_id` won't make it for the LDK release, but that doesn't mean it shouldn't make it for the initial spec release, right? Especially since cross-compat tests haven't been made yet, and will likely require an iteration cycle with code changes (since we want two interoperable implementations before merging the spec change). I'd consider that the first implementation releases with Bolt 12 support should be experimental and allow us to test cross-compat, and we'll need at least one more release cycle to drop that experimental flag and freeze the spec. IMO this change should make it into the spec during that cycle :)

**Comment by t-bast** [comment]
> @jkczyz did indicate he'd look at it today so maybe we can still slip it in, but no promises.

If that can be done for the reader side, that would be great! Otherwise that will be for the next release then.

> This isn't entirely true. LNDK has things working with eclair and we've made some progress with CLN just waiting for some blinded path "who connects" compat changes in CLN. At this point, we're ready for cross-compat tests, and as far as I'm aware eclair is too. That means, as far as I'm concerned, we're ready to go here.

I didn't know you were at that point, is there a place where we can track cross-compat tests (which would allow multiple people to contribute to the testing effort as well and report on the results)?

On the eclair side, we still have a few changes we'd like to make (improvements discovered when implementing the wallet side of things), we should be ready as well in a couple of weeks. Looking forward to making those tests!

**Comment by carlaKC** [comment]
Transcript: https://github.com/bitcointranscripts/bitcointranscripts/pull/477
