### ISSUE TITLE
Lightning Specification Meeting 2024/05/06

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1161]
The meeting will take place on Monday 2024/05/06 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [ ] Spec clean-up #1092
- [ ] Channel closing block delay follow-up #1156
- [ ] Constant size failure onion decryption #1154
- [ ] Notation for math content #1158
- [ ] Offers #798
- [ ] Quiescence #869
- [ ] Splicing #863 #1160
- [ ] Liquidity ads #878 #1145 #1153
- [ ] Dynamic Commitments #1117 vs Upgrade on Reestablish #868
- [ ] Taproot #995
- [ ] Taproot gossip #1059
- [ ] Async payments #1149
- [ ] Peer storage backup #881 or #1110
- [ ] Channel jamming #1043 #1071 https://github.com/lightning/blips/pull/27
- [ ] DNS-based offers #1136
- [ ] Attributable errors #1044
- [ ] Clarify `channel_reestablish` requirements #1049 or #1051

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] Simplified mutual close #1096
- [ ] Trampoline routing #829 and #836
- [ ] Zero reserve #1140 (follow-up on #1133 to include a feature bit)
- [ ] Don't force close until error is received after `channel_reestablish` #934

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] Simplified commitment #867
- [ ] lnprototest (https://github.com/rustyrussell/lnprototest)

**Comment by ellemouton** [comment]
Re taproot gossip: posted some questions in the PR & pushed some updates. 

https://github.com/lightning/bolts/pull/1059#issuecomment-2095585581

Main question is around the use of the new messages for both existing, legacy channels & new, legacy channels

**Comment by valentinewallace** [comment]
Re: trampoline, would like to discuss this spec feedback on trampoline <> blinded paths: https://github.com/lightning/bolts/pull/829#discussion_r1591173093

**Comment by Roasbeef** [comment]
channel update error issues:
  * potentially can fingerprint senders by sending out unique `channel_update` values 
  * should we remove it all together? 
     * would eliminate a finger printing vector 
     * but, may add additional UX issues, as not able to get the latest update at runtime 
     * can affect mobile nodes that aren't syncing gossip all the time, if they can't get the latest updates, payments may never happen
  * can do in two phases:
     1. say it's optional for now 
     2. remove the text about applying and broadcasting

BOLT 12 stuff:
  * CLN doesn't do direct connect for invoice replies, just for sending
     * would say not connected, can't reply, working on adding that portion 
  * https://github.com/lightning/bolts/pull/798#discussion_r1577991911
 
trampoline: 
  * question re interaction of blinded paths + trampoline 
  * async payments interaction:
     * looks like sender is setting the CLTV 
     * async payments wants a very long CLTV 
     * maybe looking at letting a trampoline node extend it themselves

stfu:
   * seems that won't be adding termination?
      * for all updates, you have a state where you get to be half committed
      * can't abort, but only one side has exchanged secret data
      * can always end up here during disconnect, handled during channel reest 
      * if we add `go-on`, then we can end up in a half committed state if you haven't d/c'd from peer?
         * do you put chan reest mid protocol? 
         * or can try some state sync protocol 
         * why go thru the extra effort? 
         * instead centralize logic, and use disconnect/chan-reest otherwise 

splicing:
   * new splicing PR!!
     * old one was still in draft, latest here: https://github.com/lightning/bolts/pull/1160 
   * still have a dep on stfu

liquidity ads:
   * working on a PoC of JIT channels
     * flexibility in how you pay, liquidity ads used to advertise fees
     * how would ppl reject?
         * phoenix: set a fee budget, automatic accept, otherwise fail
    * t-bast working on bLIP for JIT channel open 
      * includes a `will_send_htlc` message, has the onion, proves there's actually an HTLC, etc, etc

gossip v1.5:
  * motivation for old+new channels in v1.5?
     * block height for channel updates
         * can add to old chan update? 
      * also need re-negotiation logic as well
