### ISSUE TITLE
Lightning Specification Meeting 2024/06/03

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1167]
The meeting will take place on Monday 2024/06/03 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Spec clean-up #1165
- [x] Optional `channel_update` in error onions #1163
- [x] Offers #798
- [x] Quiescence #869
  - @rustyrussell can you (or someone else with access to the branch) rebase the PR? We've started cross-compat tests between eclair and lnd, it's looking good, so we should be able to merge it soon
  - there are also a couple of comments asking for some small additions to clarify a few subtleties, but nothing major
- [x] Splicing #863 #1160
- [x] Liquidity ads #878 #1145 #1153
- [ ] ~Dynamic Commitments #1117 vs Upgrade on Reestablish #868~
- [ ] ~Taproot #995~
- [ ] ~Taproot gossip #1059~
- [ ] ~Async payments #1149~
- [ ] ~Peer storage backup #881 or #1110~
- [ ] ~Channel jamming #1043 #1071 https://github.com/lightning/blips/pull/27~
- [ ] ~DNS-based offers #1136~
- [ ] ~Attributable errors #1044~
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Constant size failure onion decryption #1154~
- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Simplified mutual close #1096~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Zero reserve #1140 (follow-up on #1133 to include a feature bit)~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Simplified commitment #867~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by carlaKC** [comment]
I'm not going to make this meeting - please will somebody record it for transcription!

Only update from me is that https://github.com/lightning/blips/pull/27 is ready for mergo (IMO) and the LND implementation is up to date with current blip.

**Comment by Roasbeef** [comment]
spec clean up:
  * left over sections that ref non-zero fee anchors and pubkey rotation
  * now removed
  * other interop instance in the wild:
     * CLN stopped setting the TLV onion bit 
     * older nodes may still use that value to decide if TLV onion should be used or not
     * new lnd can start to assume bit, old will take some time to update

optional channel update:
   * today nodes already treat it as optional in the onion error, spec says it's mandatory, should address that 
   * can also soften the language 

offers:
  * BOLT 12 for bundled payments
    * if you recv an invoice request, but don't have the capacity 
    * sends two payment hashes: user pays one for chan open, then another for the actual payment 
      * downside of 2 payments for the sender, and also needs to actually know of it 
      * griefing vector, something up to the pricing of the end user or service 

stfu:
  * needs some final clarifications
  * once those are done, and PR is rebased, then should be g2g
  * lnd <-> eclair compat achieved 

splicing:
  * new PR should be reviewed, matches eclair impl
  * main diffs:
    * which TLVs are added to commit sig, revoke and ack, and the other messages
    * ensures some edge cases work properly w/o it, undefined

rbf-coop close:
  * lock time cross compat to be interop tested, then g2g

gossip 1.75:
   * two independent protocols going forward, all nodes need to advertise both versions
