### ISSUE TITLE
Lightning Specification Meeting 2024/07/01

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1175]
The meeting will take place on Monday 2024/07/01 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Optional `channel_update` in error onions #1163 or #1173
- [x] Clarify blinded path `max_cltv_expiry` #1176
- [x] Blinded paths in Bolt 11 invoices: https://delvingbitcoin.org/t/blip-bolt-11-invoice-blinded-path-tagged-field/991
- [x] Offers #798
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] Channel jamming #1043 #1071 https://github.com/lightning/blips/pull/27
- [x] Async payments #1149
- [x] Splicing #863 #1160
- [x] Dynamic Commitments #1117 vs Upgrade on Reestablish #868
- [x] Liquidity ads #878 #1145 #1153
- [x] Peer storage backup #881 or #1110
- [x] DNS-based offers #1136
- [x] Attributable errors #1044
- [x] Clarify `channel_reestablish` requirements #1049 or #1051

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [x] Constant size failure onion decryption #1154
- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Simplified mutual close #1096~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Zero reserve #1140 (follow-up on #1133 to include a feature bit)~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Simplified commitment #867~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by Roasbeef** [comment]
blinded paths example:
  * example in the spec had an issue:
      * https://github.com/lightning/bolts/issues/1174
      * https://github.com/lightning/bolts/pull/1176
  * implementation in eclair matches the fix 
  * need to set min expiry delta expiry in the encrypted data to yourself 
    * otherwise, you may risk having a payment rejected 
  * also exposes potential gap in routes that have a very short expiry
  * mulling of an alternate direction: partial onion

blinded paths in legacy invoice format:
  * blinded paths have to use it
     * has a required feature bit
     * no hop hints 
     * random pubkey (not actually in graph)
  * could also expose via bolt12 invoice as well, would need to ignore some existing fields

Offers:
  * shipping Phoenix w/ BOLT12 this week! on testnet rn, tested w/ LDK, minor issue w/ CLN interop
  * edge case re blinded paths:
     * if you give us a blinded path that leads to us, need to detect it
  * dummy hops:
     * for the Offer only use a single hop
     * for the actual blinded path invoice, use 3 of them, one of them is the real node (6 nodes by default?) 

taproot:
  * bug fixes for 2 issues roasbeef brought up addressed (sequence mismatch, and local/remote script pattern matching)
  * eclair nearly finished implementation wise
     * need to add a commit to add extra nonces for the splice use case

channel jamming:
  * lnd now has APis that allow deciding if the endorsement bit should be propagated or not
  * carla working on integrating new APIs for more dynamic logic 

async payments:
  * pushed update modifying a feature bit in the onion 
  * waiting for feedback 
  * lot of focus on shipping BOLT12, can check this out more deeply after shipped

splicing:
  * dusty checking out the spec again 
  * eclair doesn't support with custom channels, using temporary values and messages types for public channels 
  
dyn commits:
  * splitting dyn commits into kick off related stuff, and just the param or commitment output changes
  * 3 diff categories:
    * changes to boundaries on state space (max htlc, etc)
    * change to params to render state into a commitment txn (needs re-signing, anchor update, etc)
    * funding output conversion (may use kick off)

liquidity ads:
  * nearly completed impl of on the fly funding, looking for feedback on the format, etc
