### ISSUE TITLE
Lightning Specification Meeting 2024/07/29

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#1185]
The meeting will take place on Monday 2024/07/29 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Recently Updated Proposals / Seeking Review

This section contains changes that have been opened or updated recently and need feedback from the meeting participants.

- [x] Clarify route blinding spec #1182
- [x] gossip_status #1186 
- [x] Offers #798
- [x] Bolt 12 contacts / mutual message auth (https://github.com/lightning/blips/pull/31 and https://github.com/lightning/blips/pull/42)
- [x] Taproot #995
- [x] Taproot gossip #1059
- [x] Channel jamming #1043 #1071 https://github.com/lightning/blips/pull/27
- [x] Liquidity ads #878 #1153
- [x] Async payments #1149
- [x] Splicing #863 #1160
- [ ] ~Dynamic Commitments #1117 vs Upgrade on Reestablish #868~
- [ ] ~Peer storage backup #881 or #1110~
- [ ] ~DNS-based offers #1136~
- [ ] ~BIP 353 name in offers #1180~
- [ ] ~Attributable errors #1044~
- [ ] ~Clarify `channel_reestablish` requirements #1049 or #1051~

## Stale Proposals

This section contains pending changes that may not need feedback from the meeting participants, unless someone explicitly asks for it during the meeting. These changes are usually waiting for implementation work to happen to drive more feedback.

- [ ] ~Inbound fees https://github.com/lightning/blips/pull/18 and https://github.com/lightning/blips/pull/22~

## Waiting for interop

This section contains changes that have been conceptually ACKed and are waiting for at least two implementations to fully interoperate.
They most likely don't need to be covered during the meeting, unless someone asks for updates.

- [ ] ~Simplified mutual close #1096~
- [x] Trampoline routing #829 and #836
- [ ] ~Zero reserve #1140 (follow-up on #1133 to include a feature bit)~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~

## Long Term Updates

This section contains long-term changes that need review, but require a substantial implementation effort.

- [ ] ~Simplified commitment #867~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by Roasbeef** [comment]
blinded paths for payments:
  * use blinded paths before the introduction point?
    * do we gain anything by adding one from the sender?
    * part of the onion rework: https://github.com/lightning/bolts/pull/1182#discussion_r1680923613
  * how do ppl handle dummy paths?
     * when you add dummy hops, do you also add extra fees in addition to CLTV values?
       * fees may make it look more legit, but at the cost of actually increasing fees for the sender
       * the sender can eat all the fees themselves? 
       * are there other probing vectors w/ zero fees? 
     * what values do people use?
        * lnd today: all the hops are padded out to the same value
        * CLN today: wanting to settle on a value of 3, still a fixme


gossip status:
  * you tell a peer your stats, and then they decide just to flood you with everything 
    * inspired to want to fast catch up a node that was offline for a long time
  * reintroducing the old initial gossip dump, but with more context
  * some impls already ask for all the gossip on reconnect 
  * zooming out:
    * have all found weird issues with gossip, haven't cohesively tracked them all down 
    * should we add more band-aides vs going for the bigger re-work?

offers:
  * CLN implementation caught up, others should be able to test against the master branch 
  * invoice errors:
     * expected only from invoice requests, or invoices as well?
     * should be able to send an error in response to an invoice
       * you can't reply if you don't send a reply path though 
       * or you can just send via the invoice request
          * unless impls have stricter logic re how you can send messages and with which paths
          * stateless approach would allow though 
  * recurrent stuff moved over into the set of experimental ranges

bolt 12 contact list:
  * wanting to have a feature like a contact list, shows that your friends paid you again 
  * before:
    * used the payer key in the offer 
    * forces linking to a single offer, or having to re-use a payment key for future offers
  * should we do something else? 
    * can derive some "contact key", bootstrapped somehow, used to allow linking
      * but then need a way to distribute the keys, in the URI? or BIP 353?
      * can then include in the encrypted payment data, so then sender doesn't necessarily see the correlation 
   * does the issuer field allow us to handle this?
      * issuer field, then some comment? 
    * key exchange protocol when you first pay 
       * also some overlap with nostr, working on key distribution web-of-trust-y thing 
    * what are the ideal properties? 
       * recipient can only see someone paid when you're mutually in the contact list of the other:
         * A learns only if both A and B are in each other's contact list
     * LDK has transient payer key by default, Eclair evaluating hybrid approach 

taproot:
  * eclair working on the splicing side of things, re extra nonces 

taproot gossip:
  * lnd working on getting back to, working on blinded paths stuff

channel jamming:
   * been some recent discussion re channel jamming 
   * down to bike shedding on values for the bLIP
       * is a binary value enough, or should we use some integer range?
       * simple version: 0 is unendorsed -- up to you re interpretation
   * is the extra level of granularity actually useful?
     * could use the 0-7 as a percentage of success? 
       * could use some historical data, but requires existing payment attempts through the node?
     * would be useful to have some numbers re the ranges:
       * code is almost ready, blocked on deciding what to do if not running reputation code 
    * proposal: only forward on endorsed if fully endorsed, otherwise drop to 0 

splicing:
  * Eclair has a PR to start using official values, so can run interop with 

trampoline:
  * more work re how to combine trampoline and blinded paths, t-bast posted some commits 
  
liquidity adds:
   * updated spec based on past comments, ready to review 

nLightning:
   * new impl on the block: https://github.com/ipms-io/nlightning
   * doing BOLT 2 and 3
   * finished: BOLT 8, 9, 10, 11
   * started to BOLT 11 as well 
   * ideal path to a new impl?
      * wanted to go from 1 to 11, realized need to take a diff approach
