### ISSUE TITLE
Lightning Specification Meeting 2021/10/25

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#929]
The meeting will take place on Monday 2021/10/25 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video call will be available at https://meet.google.com/vxa-nxpp-krh to allow higher bandwidth discussion on some topics.

## Pull Request Review

- [x] Move repository to lightning organization #925
- [x] Anchor outputs clean-up #903
- [x] Add dust exposure threshold #919
- [x] Drop ping sending limitation #918
- [ ] ~Feature bit for channel type #906~
- [ ] ~Simple turbo channels enablement #910~
- [ ] ~Warning messages #834~
- [ ] ~Advertize compression algorithms in `init` #825~
- [ ] ~Add payment metadata to payment request #912~
- [x] Dynamic DNS support in gossip messages #911 or #917
- [ ] ~BLIPs #884~

## Long Term Updates

- [ ] ~Dual funding #851~
- [ ] ~Splicing #863~
- [ ] ~Blinded paths #765~
- [ ] ~Onion messages #759~
- [ ] ~Offers #798~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Peer storage backup #881~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~Hornet~
- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by TheBlueMatt** [comment]
We've already had a large issue with forgetting what we talked about two weeks ago, I'm not a big fan of moving to video chat which only makes that problem worse. If we want video chat for specific subjects that need higher-bandwidth communication that seems reasonable but just saying that the whole meeting should alternate doesn't seem useful.

**Comment by BitcoinErrorLog** [comment]
Some of our team would like to join these calls, is it at all possible to have them at a more friendly time for Westerners? If not it is okay, but is it also possible to create a calendar that we can add to Google Cal?

**Comment by t-bast** [comment]
> is it at all possible to have them at a more friendly time for Westerners?

It's very unlikely that we'll change this meeting time. We have regular contributors in this meeting from Europe, the US and Australia, so there's simply no time that is great for everyone. To be fair, westerners don't have that much to complain here, Australian contributors have to wake up very early (5:30am) to attend!

> is it also possible to create a calendar that we can add to Google Cal?

Sure, I can share that with you, give me an email address and I'll forward it.
