### ISSUE TITLE
Lightning Specification Meeting 2021/12/06

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#943]
The meeting will take place on Monday 2021/12/06 at 7pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Pull Request Review

- [x] Add payment metadata to payment request #912
- [x] Advertize compression algorithms in `init` #825
- [x] Dynamic DNS support in gossip messages #911 or #917
- [x] BLIPs #884
- [ ]  ~Simple turbo channels enablement #910~
- [ ] ~Anchor outputs clean-up #903~
- [x] Route blinding #765
- [x] Onion messages #759
- [ ] ~Warning messages #834~
- [x] Clarify `channel_reestablish` requirements #932
- [ ] ~Add dust exposure threshold #919~
- [ ] ~Drop ping sending limitation #918~

## Long Term Updates

- [ ] ~Dual funding #851~
- [ ] ~Liquidity ads #878~
- [ ] ~Splicing #863~
- [ ] ~Offers #798~
- [x] Simplified commitment #867 
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Peer storage backup #881~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by t-bast** [comment]
@michaelfolkson sorry for the late notice, if you're available to do transcripts for this meeting it would be great!
If you prefer something else than Google Meet, simply provide a link that lets anyone join the meeting without installing any software and we should be good to go.

**Comment by michaelfolkson** [comment]
@t-bast: Sure, it is in my diary now.

The transcript from the last spec meeting: https://btctranscripts.com/lightning-specification/2021-11-22-specification-call/

Let's try Jitsi (open source, Tor support) as a number of people expressed a preference for it last time: https://meet.jit.si/Lightning-Spec-Meeting

If there are any problems we can always fall back to Google Meet.

**Comment by michaelfolkson** [comment]
Btw if anyone wants their personal comments in future transcripts to be attributed let me know. By default I will anonymize unless someone lets me know otherwise. But it is totally individual preference.

**Comment by t-bast** [comment]
I'm fine with anonymizing comments by default, in theory it lets readers focus on the content, not on individuals.

**Comment by michaelfolkson** [comment]
Transcript: https://github.com/michaelfolkson/bitcointranscripts/blob/lightning-2021-12-06/lightning-specification/2021-12-06-specification-call.md

**Comment by t-bast** [comment]
Thanks @michaelfolkson :+1:
