### ISSUE TITLE
Lightning Specification Meeting 2022/05/09

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#986]
The meeting will take place on Monday 2022/05/09 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Pull Request Review

- [x] Onion failures with channel updates #979
- [x] Clarify mutual close requirements #985
- [ ] ~Route blinding #765~
- [ ] ~Onion messages #759~
- [ ] ~Offers #798~
- [ ] ~Add dust exposure threshold #919~
- [ ] ~Port conventions for different networks #968~
- [ ] ~`gossip_timestamp_filter` behavior clarification #980~

## Waiting for interop

- [x] Simple turbo channels enablement #910
- [x] Dual funding #851
- [ ] ~Websocket transport #891~
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~
- [ ] ~Dynamic DNS support in gossip messages #911~

## Long Term Updates

- [ ] ~Liquidity ads #878~
- [ ] ~Splicing #863~
- [ ] ~Simplified commitment #867~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Peer storage backup #881~
- [ ] ~Anonymous gossip~
- [ ] ~Taproot updates~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by ksedgwic** [comment]
Was there a calendar invite for this meeting?  I think I tried one last time but it had bugged permissions?

**Comment by Roasbeef** [comment]
Interop update:
  * Eclair ready to do dual funding interop w/ CL needs an updated version to test against. 
    * Re RBF: CL has an RPC mechanism to trigger an update
    * Has some cross over with splicing potentially 

On splicing:
* Half baked idea from roasbeef: re-use the anchor outputs in the splicing transaction to give verifiers an on-chain signal that this is actually a splicing transaction. A `channel_announcement` would then signal explicitly if the channel is splice-able or not

**Comment by Roasbeef** [comment]
Zero conf:
 * From decker working on it: what if some features in the channel type TLV were optional, able to flag "maybe" zero conf, then the responder can signal if they accept it or not (?). 
 * From eugene: doesn't specify that you shouldn't chose alias A if it conflicts with a pre-existing or future channel (seems to be underspecified)
