### ISSUE TITLE
Lightning Specification Meeting 2022/05/23

### ISSUE THREAD

**Issue by t-bast** [lightning/bolts#992]
The meeting will take place on Monday 2022/05/23 at 8pm UTC (5:30am Adelaide time) on Libera Chat IRC [#lightning-dev](irc://irc.libera.chat/lightning-dev). It is open to the public.

A video link is available for higher bandwidth communication: https://meet.jit.si/Lightning-Spec-Meeting

## Pull Request Review

- [x] Clarify coop close requirements #970
- [x] Hold htlcs before forwarding #989
- [x] Route blinding #765
- [x] Onion messages #759
- [x] Offers #798
- [x] Add dust exposure threshold #919
- [x] Port conventions for different networks #968

## Waiting for interop

- [x] Handle `update_fee` during `shutdown` #972
- [x] Graph dump on `gossip_timestamp_filter` #980
- [x] Simple turbo channels enablement #910
- [x] Dual funding #851
- [x] Websocket transport #891
- [ ] ~Don't force close until error is received after `channel_reestablish` #934~
- [ ] ~Dynamic DNS support in gossip messages #911~

## Long Term Updates

- [ ] ~Liquidity ads #878~
- [ ] ~Splicing #863~
- [ ] ~Simplified commitment #867~
- [ ] ~Trampoline routing #829 and #836~
- [ ] ~Upfront payments / DoS protection #843~
- [ ] ~Peer storage backup #881~
- [ ] ~Anonymous gossip~
- [ ] ~Taproot updates~

## Backlog

The following are topics that we should discuss at some point, so if we have time to discuss them great, otherwise they slip to the next meeting.

- [ ] ~lnprototest (https://github.com/rustyrussell/lnprototest)~

**Comment by t-bast** [comment]
I won't be able to attend this spec meeting, but I'll see most of you IRL soon!

**Comment by Roasbeef** [comment]
Re #989 (convo between rusty+roasbeef+cdecker): seems there's some overlap here w/ Trampoline potentially? Adding more Trampoline-like functionality here would allow the _LSP_ to retry the payment internally which would give us better UX as the client can go offline completely and allow the LSP to retry the payment. Otherwise, the LSP just gets one shot, and can't retry afterwards since they can't re-use the onion (due to Sphinx replay protection).

**Comment by Roasbeef** [comment]
Re onion messaging: ppl starting to make more concrete sketches for rate limiting (back propagation?). More to be discussed in meatspace.

**Comment by t-bast** [comment]
Thanks for the summary @Roasbeef!
